### ISSUE TITLE
One env only values hints

### ISSUE THREAD

**Issue by kapodes** [microconfig/microconfig-idea-plugin#1]
Currently if we have an `application.local.yaml` referring to other component via `${component@key}` and that component only has `application.local.yaml` we get a hint with all current ENVs excluding `local` showing `ERROR`.

Instead hint should only show `local` ENV value.

current hint:

```
${component@key}

base: ERROR
local: value
prod: ERROR
test: ERROR
```

proposed hint:

```
${component@key}

local: value
```

**Comment by alxmatorin** [comment]
implemented
