### ISSUE TITLE
plugin must scroll to placeholder's defenition after 'move to file'

### ISSUE THREAD

**Issue by alxmatorin** [microconfig/microconfig-idea-plugin#5]
after move commnad (cntrl) Plugin jumps to the placeholder's source file, sets curson to the placehodler's line, but doesnt scroll to it. So if the source file contains a lot of lines, curson is not visible.

**Comment by microconfig** [comment]
fixed

**Comment by microconfig** [comment]
foxed

**Comment by alxmatorin** [comment]
fixed
